### PR TITLE
Fix #45 and #47

### LINKED ISSUE #45: Test fails for Python 3.x ('reduce' not defined)
Currently, the test fails for Python 3.x due to `reduce` not being defined.

```
======================================================================
ERROR: test_iterator (__main__.FingerTreeDequeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 1086, in test_iterator
    self.assertEqual(sum(range(1,20)), sum(Deque.from_iterable(range(1,20))))
  File "/home/microamp/devel/projs/fn.py/fn/immutable/finger.py", line 138, in from_iterable
    return FingerTree.from_iterable(lambda x: x, it)
  File "/home/microamp/devel/projs/fn.py/fn/immutable/finger.py", line 122, in from_iterable
    return reduce(lambda acc, curr: acc.push_front(curr), it, tree)
NameError: global name 'reduce' is not defined

----------------------------------------------------------------------
Ran 123 tests in 0.110s

FAILED (errors=1)
```

### PR DESCRIPTION
**Pull request by microamp**
This should fix #45 and #47.

The latter appears to be a bug in the PyPy version on Traivs (PyPy 2.2.1 with GCC 4.6.3) which seems to have been addressed in a later version. I could not reproduce the error with PyPy 2.3.0-alpha0 running locally. The alternative solution in the pull request is not as elegant as `collections.namedtuple`, but it would help us move on without having to wait for the next stable release of PyPy.

In addition to the above two, I've
- fixed a naming conflict issue between `immutable.list.Deque` and `immutable.finger.Deque`, and
- added Python 3.4 to the Traivs config

### CODE REVIEW

**Comment by microamp** [comment]
Please note that slots have been added to the finger trees now.

**Comment by microamp** [comment]
@kachayev, have you had a look at this by any chance?

It'd be good to get over this hump. I see five other pull requests failing to pass because of #45 and #47.

**Comment by kachayev** [comment]
@microamp unfortunately I don't have much time just now, I'll take a look tomorrow and try to manage all opened RPs/bugs.

**Comment by kachayev** [comment]
Ok, I'm merging this, thanks for help! I wonder what the problem is with namedtuple(s). Will take some time to investigate this issue deeper.

**Pull request merged**
