### PR TITLE
Scala-style partial operator binding fails on 3+ underscores.

### PR DESCRIPTION
**Pull request by pyos**
The current implementation of `underscore.py` fails with some scary-looking error messages if more than one underscore per operator is used. For example:

``` python
> (_ + _ * _)(1, 2)
TypeError: unsupported operand type(s) for +: 'int' and 'function'

  in <stdin> line 1, `<module>`: None
  in ./fn/underscore.py line 64, `__call__`: return curry(self._callback, *args)
  in ./fn/op.py line 27, `curry`: return curry(f(arg), *rest) if rest else f(arg)
  in ./fn/op.py line 27, `curry`: return curry(f(arg), *rest) if rest else f(arg)
  in ./fn/underscore.py line 18, `<lambda>`: call = lambda arg1: lambda arg2: f(self(arg1), other(arg2))
```

Unfortunately, the current underscore implementation was too cryptic for me to understand :) That's why the attached commits rewrite it completely. But hey, at least it works now! :)

``` python
> (_ + _ * _)(1, 2)
<lambda>
> (_ + _ * _)(1, 2, 3)
7
```

(As a side note, I took the liberty of changing the string representations so that the `eval(repr(x)) == x` rule holds.)
(EDIT: Sorry if I messed up the pull request. I hope it won't be too hard to merge it. :)

### CODE REVIEW

**Comment by kachayev** [comment]
I understood the problem with arity errors and I thought much about how to ensure that error message will be clear enough. `(_ + _ * _)(1, 2)` should raise something like `ValueError("Arity exception: Function accepts 3 arguments, 2 given")`. I'm not sure that I understood your proposal right: `(_ + _ * _)(1, 2)` returns function that accepts third argument and return result (like Haskell does)? So

``` python
> (_ + _ * _)(1, 2)
<lambda>
> (_ + _ * _)(1, 2)(3)
7
> (_ + _ * _)(1, 2, 3)
7
```

**Comment by kachayev** [comment]
Regarding to reimplementation of printing `_`-based functions: the origin idea was to clarify for user what function will do with arguments. I don't see, why use

``` python
>>> print(_ + _*_)
"_ + _ * _"
```

What additional information can I get from this notation? Previously implemented functionality gave you human-readable function:

``` python
>>> print(_ + _*_)
"(x1, x2, x3) => (x1 + (x2 * x3))"
```

I agree that, `eval(repr(x)) == x` is a good style, but to deal with this we need to reimplement only `__repr__` (not whole functionality).

**Comment by pyos** [comment]
> I'm not sure that I understood your proposal right: (_ + _ \* _)(1, 2) returns function that accepts third argument and return result (like Haskell does)? 

Yes, you understand it right: calling a function with multiple underscores substitutes them for values from left to right. This is NOT the  point of this pull request, however: `(_ + _ * _)(1, 2, 3)` didn't work in the old underscore.py implementation either:

``` python
> (_ + _ * _)(1, 2, 3)
TypeError: unsupported operand type(s) for +: 'int' and 'function'

  in <stdin> line 1, `<module>`: None
  in ./fn/underscore.py line 64, `__call__`: return curry(self._callback, *args)
  in ./fn/op.py line 27, `curry`: return curry(f(arg), *rest) if rest else f(arg)
  in ./fn/op.py line 27, `curry`: return curry(f(arg), *rest) if rest else f(arg)
  in ./fn/underscore.py line 18, `<lambda>`: call = lambda arg1: lambda arg2: f(self(arg1), other(arg2))
```

The problem seems to be that your `fmap` implementation assumes all `_Callable` instances require exactly one argument, while `_ * _`, obviously, needs two. So it tries to add `1` to `(2 * _)` _even if there's a third argument_ and fails.

> What additional information can I get from this notation?

You get exactly as much information as you did from the old representation (and from the code you write to create a function, for that matter). The only differences are that it's shorter and it can be `eval`ed.

**Comment by kachayev** [comment]
> Yes, you understand it right: : calling a function with multiple underscores substitutes them for values from left to right

This is really good idea in Haskell (in lambda calculus if you want so), but in dynamically typed Python this will lead to confusion in many cases, cause

``` python
>>> bool(lambda x: x * 2)
True
```

and that's why

``` python
>>> filter(lambda f1: lambda f2: f1 < f2, range(5))
[0, 1, 2, 3, 4]
```

you don't know that you made a terrible mistake here. So, I prefer to raise here some `ArityError` as I already mentioned.  

> however: `(_ + _ * _)(1, 2, 3)` didn't work in the old `underscore.py` 

This issue I'll check, possible this functionality was broken with one of the changes.

> You get exactly as much information as you did from the old representation.

Obviously not. When you see this `"(x1, x2, x3) => (x1 + (x2 * x3))"` you know:
- number of arguments to pass
- arguments substitution order
- evaluation order

**Comment by pyos** [comment]
> you don't know that you made a terrible mistake here. So, I prefer to raise here some ArityError as I already mentioned.

I see your point, and you're probably right. However, as I already mentioned, this is not what the pull request is about. When writing this code, I merely replicated the original behavior.

``` python
> (_ + _)(1)
<function fmap.<locals>.applyier.<locals>.<lambda>.<locals>.<lambda> at 0x7f20d297ae60>
> (_ + _)(1)(2)
3
```

> When you see this "(x1, x2, x3) => (x1 + (x2 \* x3))" you know:
> number of arguments to pass

= number of underscores.

> arguments substitution order

From left to right.

> evaluation order

Parentheses are still there. And, as I already said, the representation conveys as much information _as the code itself_. If copy-pasting code into the interactive prompt is required to understand it, that's probably a bad piece of code, isn't it?

**Comment by pyos** [comment]
I also made [a version that raises `ArityError`](https://github.com/pyos/fn.py/tree/fixed-arity-underscore) when called with invalid number of arguments.

``` python
> (_ < _)(2, 3)
True
> (_ < _)(2, 3, 4)
ArityError: (_ < _) expected 2 arguments, got 3

  in <stdin> line 1, `<module>`: None
  in ./fn/underscore.py line 44, `__call__`: raise ArityError(self, self._arity, len(args))

> (_ < _)(2)
ArityError: (_ < _) expected 2 arguments, got 1

  in <stdin> line 1, `<module>`: None
  in ./fn/underscore.py line 44, `__call__`: raise ArityError(self, self._arity, len(args))
```

**Comment by kachayev** [comment]
I just pushed lates changes https://github.com/kachayev/fn.py/commit/fa64cf5878447b7d0b80e53235c03ab66e3bb5d4:
- `ArityError` (thanks for implementing this, I took most code from your branch)
- Fixed error with `_ + _ * _` and other similar functions, relevant test cases are also included
- `eval << repr == identity` as to say (this means that `eval(repl(x)) == x`

I'm still not happy with code of `underscore` module, and I will continue working with cleaning code to clarify the nature of all operations and make it little bit more readable. In any case, can I close this issue or do you have other comments on described problem?

**Comment by pyos** [comment]
> In any case, can I close this issue or do you have other comments on described problem?

That was all I wanted to say (at least for now, :) and your commit seems to work just fine, so I'm closing the pull request.

**Pull request closed without merging**
